Feature/46
mash-up-kr/Elegant_Spring_Family_Member pull request #49
Opened 2021-09-03 03:24 UTC by chlalstjd430

resolve #46 

/login 페이지에서 OAuth 인증 제공자 선택
/login/naver 페이지에서 Naver 로그인 페이지로 redirect
/login/naver/callback 페이지에서 필요한 정보 획득 및 회원 가입/로그인 처리 (code -> accessToken -> userInfo)

+ LoginService,OAuthAccessTokenService 이 쪽 변경되 부분이 있어서 확인 부탁드립니다.

2021-09-03 12:39 UTC, junhaesung requested changes
금방만들어주셨네요 ㅋㅋㅋ
코멘트 몇개 추가했는데 확인 부탁드려요!

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +            throw RuntimeException("state 값이 일치하지 않음. queryParam.state: $state, session.state: $state")
session.state 는 `httpSession.getAttribute("state")` 값으로 로깅해야 될 것 같습니다. 
제가 만들때부터 틀렸었네요 ㅠㅋㅋ

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/resources/application.yml
> +      client:
들여쓰기가 달라보이는데 확인부탁드려요! (8라인보다 2칸 들여써야 할거같은데 4칸으로 보이네요)

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/kotlin/mashup/backend/spring/member/infrastructure/naver/NaverUserService.kt
> +            println(exchange.body)
테스트코드같은데 정리부탁드려요!
기록 필요한 내용이라면 logger 사용하면 좋을 것 같습니다.

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/kotlin/mashup/backend/spring/member/infrastructure/naver/NaverData.kt
> +data class Response(
혹시 클래스이름이 중복될 수도 있을거같아서, NaverResponse 등으로 prefix 붙이면 좋을거같습니다.

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/kotlin/mashup/backend/spring/member/infrastructure/naver/NaverData.kt
> +        val profileImage: String?, // "https://avatars.githubusercontent.com/u/88278320?v=4"
주석은 github 내용같은데 삭제부탁드려요!

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/kotlin/mashup/backend/spring/member/infrastructure/naver/NaverData.kt
> +// reponse
response 오타인 것 같습니다.

2021-09-03 12:39 UTC, junhaesung commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +        val memberResponse = loginService.loginWithNaver(code, state)
url 이 모두 `/login/{providerName}/callback` 패턴으로 정해질 수 있다면, 컨트롤러나 서비스도 일반화할 수도 있겠네요! 
ex) `loginWithOAuth(providerName, code, state)`

2021-09-03 14:03 UTC, chlalstjd430 commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +        val memberResponse = loginService.loginWithNaver(code, state)
맞아요, 코드 보다보니 공통화 할 부분이 많아보이던데 이거 제가 함 만져볼게요 ㅎㅎ

2021-09-03 14:03 UTC, chlalstjd430 commented on api/src/main/kotlin/mashup/backend/spring/member/infrastructure/naver/NaverData.kt
> +data class Response(
아 이거 json 컨버팅 하는게 안되서 임시로 한건데 수정을 못했네요...

2021-09-03 14:04 UTC, chlalstjd430 commented on api/src/main/kotlin/mashup/backend/spring/member/infrastructure/naver/NaverUserService.kt
> +            println(exchange.body)
졸면서 코딩하느라 ㅋㅋㅋ정리가 안된게 꽤 있네요..

2021-09-03 14:09 UTC, chlalstjd430 commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +            throw RuntimeException("state 값이 일치하지 않음. queryParam.state: $state, session.state: $state")
github부분도 반영했습니다~

2021-09-03 14:55 UTC, chlalstjd430 commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +        val memberResponse = loginService.loginWithNaver(code, state)
@junhaesung 해성님 이거 OAuthController 만들고 템플릿 메소드 패턴 적용해서 함 해봤는데 어떠세용!? 한번 확인해주세용 ㅎㅎ~

2021-09-03 14:55 UTC, chlalstjd430 commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +        val memberResponse = loginService.loginWithNaver(code, state)
@J-Heee @YJeongKim 님들도 한번 확인해주세요!

2021-09-03 16:22 UTC, junhaesung approved these changes

2021-09-03 23:20 UTC, J-Heee commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/naver/NaverLoginController.kt
> +        val memberResponse = loginService.loginWithNaver(code, state)
오오 OAuthLoginController로 묶은 것 좋은 것 같습니다! 확인했습니다😊

2021-09-03 23:24 UTC, J-Heee approved these changes
먼저 완성해주셔서 감사합니다:)
구글 로그인 개발하면서 고민중인 부분이 있었는데,
민성님 코드 참고해서 잘 해결할 수 있을 것 같아요! 👍

2021-09-06 08:19 UTC, YJeongKim approved these changes
확인이 늦어 죄송합니다😭
템플릿 메소드 패턴 적용한 거 Good입니다!
수고하셨어요~

2021-09-06 08:19 UTC, YJeongKim commented on api/src/main/kotlin/mashup/backend/spring/member/application/LoginService.kt
> +    private fun loginWithOAuth(code: String, state: String?, idProviderType: IdProviderType): MemberResponse {
오 코드 중복 안되게 이렇게 메소드로 분리한 것 좋네요!

2021-09-06 08:19 UTC, YJeongKim commented on api/src/main/kotlin/mashup/backend/spring/member/presentation/web/oauth/OAuthController.kt
> +abstract class OAuthLoginController{
이렇게 공통화되서 너무 좋은 것 같아요!!👍

2021-09-06 08:20 UTC, merged